version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - SECRET_KEY=your-secret-key
      - DATABASE_URL=postgresql://user:password@postgres:5432/report_db
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: "2.0"

  celery:
    build: .
    command: celery -A main.celery_app worker --loglevel=info --concurrency=4
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/report_db
    depends_on:
      - redis
      - postgres
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: "2.0"

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=report_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: