version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./inputs:/app/inputs
      - ./outputs:/app/outputs
      - ./config:/app/config
    environment:
      - PYTHONUNBUFFERED=1